### ISSUE TITLE
darwin dataset comment -h gives incorrect help information

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [v7labs/darwin-py#408]
Based on this message:

```
usage: darwin dataset comment [-h] [--text TEXT] [--x X] [--y Y] [--w W] [--h H] dataset file

positional arguments:
  dataset            [Remote] Dataset name: to list all the existing dataset, run 'darwin dataset remote'.
  file               File to comment

optional arguments:
  -h, --help         show this help message and exit
  --text TEXT        Comment: list of words
  --x X              X coordinate for comment box
  --y Y              Y coordinate for comment box
  --w W, --width W   Comment box width in pixels
  --h H, --height H  Comment box height in pixels
```

One would assume that the minimal argument would be `darwin dataset comment dataset-demo`. However this is not true and it will fail:
```
There was an error posting your comment!

Traceback (most recent call last):
  File "/home/pedro/Workplace/v7/darwin-py/darwin/cli_functions.py", line 1004, in post_comment
    client.post_workflow_comment(workflow_id, text, x, y, w, h)
  File "/home/pedro/Workplace/v7/darwin-py/darwin/client.py", line 745, in post_workflow_comment
    self._post(
  File "/home/pedro/Workplace/v7/darwin-py/darwin/client.py", line 1043, in _post
    response: Response = self._post_raw(endpoint, payload, team_slug, retry)
  File "/home/pedro/Workplace/v7/darwin-py/darwin/client.py", line 1026, in _post_raw
    self._raise_if_known_error(response, urljoin(self.url, endpoint))
  File "/home/pedro/Workplace/v7/darwin-py/darwin/client.py", line 1094, in _raise_if_known_error
    raise ValidationError(body)
darwin.exceptions.ValidationError: {'errors': {'workflow_comments': [{'body': ["can't be blank"]}]}}
```

As `--text` is mandatory. The `--text` flag is currently marked as optional. 
I defend this needs to be fixed.

**Comment by owencjones** [comment]
@Fl4m3Ph03n1x Are you still working on this, or would you like me to take it into the Darwin-py backlog?

**Comment by owencjones** [comment]
Closing as stale.
