### ISSUE TITLE
dataset pull fails when export includes annotator/ reviewer metadata

### ISSUE THREAD

**Issue by filippocastelli** [v7labs/darwin-py#539]
Whenever a dataset is creted using the "include annotator/reviewer metadata" flag on, any tentative of pulling fails due to wrong JSON parsing.

This is true both using the CLI and using the Python API directly.

The issue seems to be due to the parser expecting an `email` field under a `reviewer` instance. While the field is correctly present in the `annotator` objects in the JSON response, it is not present under `reviewer` instances.

![immagine](https://user-images.githubusercontent.com/37574218/219364100-30afbc29-05c0-48e7-90bd-3291221e674e.png)

### CLI Traceback:
```
(darwin) phil@gondolin:~$ darwin dataset pull bioretics/dogs:meta001
Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/cli.py", line 37, in main
    _run(args, parser)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/cli.py", line 137, in _run
    f.pull_dataset(args.dataset, args.only_annotations, args.folders, args.video_frames, args.force_slots)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/cli_functions.py", line 421, in pull_dataset
    dataset.pull(
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/dataset/remote_dataset.py", line 269, in pull
    annotation = parse_darwin_json(annotation_path, count=None)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 419, in parse_darwin_json
    return _parse_darwin_v2(path, data)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 431, in _parse_darwin_v2
    annotations: List[Union[dt.Annotation, dt.VideoAnnotation]] = _data_to_annotations(data)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 1042, in _data_to_annotations
    image_annotations: List[dt.Annotation] = list(filter(None, map(_parse_darwin_annotation, raw_image_annotations)))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 654, in _parse_darwin_annotation
    main_annotation.reviewers = _parse_annotators(annotation["reviewers"])
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 688, in _parse_annotators
    return [dt.AnnotationAuthor(annotator["full_name"], annotator["email"]) for annotator in annotators]
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 688, in <listcomp>
    return [dt.AnnotationAuthor(annotator["full_name"], annotator["email"]) for annotator in annotators]
KeyError: 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/bin/darwin", line 8, in <module>
    sys.exit(main())
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/cli.py", line 53, in main
    fd.write(f"Command: {dumps(args, check_circular=True)}")
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Namespace is not JSON serializable
```

### Python API Traceback:
```
Traceback (most recent call last):
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/phil/.vscode/extensions/ms-python.python-2023.2.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/phil/repos/gen_scripts/dataset_management/ximage_conversion/expl.py", line 19, in <module>
    testds.dataset_obj.pull()
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/dataset/remote_dataset.py", line 269, in pull
    annotation = parse_darwin_json(annotation_path, count=None)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 419, in parse_darwin_json
    return _parse_darwin_v2(path, data)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 431, in _parse_darwin_v2
    annotations: List[Union[dt.Annotation, dt.VideoAnnotation]] = _data_to_annotations(data)
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 1042, in _data_to_annotations
    image_annotations: List[dt.Annotation] = list(filter(None, map(_parse_darwin_annotation, raw_image_annotations)))
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 654, in _parse_darwin_annotation
    main_annotation.reviewers = _parse_annotators(annotation["reviewers"])
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 688, in _parse_annotators
    return [dt.AnnotationAuthor(annotator["full_name"], annotator["email"]) for annotator in annotators]
  File "/home/phil/anaconda3/envs/darwin/lib/python3.9/site-packages/darwin/utils.py", line 688, in <listcomp>
    return [dt.AnnotationAuthor(annotator["full_name"], annotator["email"]) for annotator in annotators]
KeyError: 'email'
```
darwin-py version: 0.8.12

### Steps to reproduce: 
- Create dataset  on V7 web interface
- Create basic workflow (default annotation + review)
- Create dataset export, enable "include annotator/reviewer metadata"
- `darwin dataset pull company-name/dataset`

### Proposed solutions:
Either do a presence check on the `email` field in the `annotator` dictionary or enforce presence of that field in Darwin's backend.

**Comment by owencjones** [comment]
This should no longer be the case, but reopen if you find it is.

Many thanks for your help diagnosing issues with Darwin py

Owen V7
