### ISSUE TITLE
Python 3.7 compatibility broken

### ISSUE THREAD

**Issue by dillon-rr** [v7labs/darwin-py#579]
darwin-py has been compatible with 3.7, the [docs say that it should be compatible with 3.7](https://docs.v7labs.com/docs/use-the-darwin-python-library-to-manage-your-data), and it's important to our team that it continues to be, because we run in a 3.7 environment

darwin-py version 0.8.21

```
$ pyenv virtualenv 3.7.13 darwin-test
$ pyenv activate darwin-test
$ pip install darwin-py
$ python
Python 3.7.13 (default, Jan 30 2023, 13:08:25) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import darwin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dillon/.pyenv/versions/darwin-test/lib/python3.7/site-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/home/dillon/.pyenv/versions/darwin-test/lib/python3.7/site-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/home/dillon/.pyenv/versions/darwin-test/lib/python3.7/site-packages/darwin/dataset/local_dataset.py", line 9, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/home/dillon/.pyenv/versions/darwin-test/lib/python3.7/site-packages/darwin/dataset/utils.py", line 13, in <module>
    import darwin.datatypes as dt
  File "/home/dillon/.pyenv/versions/darwin-test/lib/python3.7/site-packages/darwin/datatypes.py", line 5, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (/home/dillon/.pyenv/versions/3.7.13/lib/python3.7/typing.py)
>
```

**Comment by dillon-rr** [comment]
Closing, we will migrate to a newer Python version
