### ISSUE TITLE
Darwin CLI error

### ISSUE THREAD

**Issue by cabreraalex** [v7labs/darwin-py#897]
Hey ya'll, I'm getting this error when running the CLI at all:

```
Traceback (most recent call last):
  File "/Users/cabreraalex/miniforge3/envs/axiom/bin/darwin", line 5, in <module>
    from darwin.cli import main
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/__init__.py", line 1, in <module>
    import darwin.dataset  # noqa
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/dataset/__init__.py", line 1, in <module>
    from darwin.dataset.local_dataset import LocalDataset  # noqa
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/dataset/local_dataset.py", line 8, in <module>
    from darwin.dataset.utils import get_classes, get_release_path, load_pil_image
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/dataset/utils.py", line 12, in <module>
    import darwin.datatypes as dt
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/datatypes.py", line 27, in <module>
    from darwin.future.data_objects.properties import PropertyType, SelectedProperty
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/darwin/future/data_objects/properties.py", line 54, in <module>
    class FullProperty(DefaultDarwin):
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 205, in __new__
    complete_model_class(
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 534, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/main.py", line 643, in __get_pydantic_core_schema__
    return handler(source)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 784, in _generate_schema_inner
    return self._model_schema(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 947, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1134, in _common_field_schema
    schema = self._apply_annotations(
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1890, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1871, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 871, in match_type
    return self._match_generic_type(obj, origin)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 895, in _match_generic_type
    return self._union_schema(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1207, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 867, in match_type
    return self._apply_annotations(source_type, annotations)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1890, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1972, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/Users/cabreraalex/miniforge3/envs/axiom/lib/python3.10/site-packages/pydantic/_internal/_std_types_schema.py", line 327, in __get_pydantic_core_schema__
    constrained_schema = core_schema.list_schema(items_schema, **metadata)
TypeError: list_schema() got an unexpected keyword argument 'fail_fast'
```

**Comment by JBWilkie** [comment]
Hi @cabreraalex thanks for raising this with us!

I can't yet be certain, but I think this could be a mismatch between the version of the `pydantic` Python library in your Python environment and the version that darwin-py requires `pydantic = ">=2.7.0"`. I've been unable to reproduce this issue when using the CLI on the most recent versions.

Could you please check:
- The version of `pydantic` in your Python environment
- That you're using the latest version of `darwin-py`, which is `1.0.3`. Since the CLI isn't currently working for you, you can use `pip list | grep darwin-py` to check

If you continue to experience issues, please reach out to our support team at support@v7labs.com. They'll be able to respond to you with much greater speed than here in GitHub.
